-- (5) magnitude analysis

 --find total customers  by counteries
 select 
	country,
	count(customer_key) as total_customer
 from [gold.dim_customers]
 group by country
 order by count(customer_key) desc

 --find total customers by gender
 select 
	gender,
	count(customer_key) as total_customers
from [gold.dim_customers]
group by gender
order by count(customer_key) desc

 --find total products by category
 select 
	category,
	count(distinct product_name) as total_products
 from [gold.dim_products]
 group by category
 order by total_products desc

 --what is the average costs in each category?
 select
	category,
	avg(cost) as average_costs
from [gold.dim_products]
group by category
order by average_costs desc

--what is the total revenue generated for each category?
select 
	p.category,
	sum(s.sales_amount) as total_revenue
from [gold.dim_products] as p
left join [gold.fact_sales] as s
on p.product_key = s.product_key
group by p.category

--what is the total revenue generated by each customer
select 
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(s.sales_amount) as total_revenue
from [gold.fact_sales] as s
left join [gold.dim_customers] as c
on s.customer_key = c.customer_key
group by 
	c.customer_key,
	c.first_name,
	c.last_name
order by total_revenue desc

--what is the distribution of sold items across countries
select 
	c.country,
	sum(s.quantity) as total_item_sold
from [gold.fact_sales] as s
left join [gold.dim_customers] as c
on s.customer_key = c.customer_key
group by c.country
order by total_item_sold desc